when:
  branch: per-7828-woodpecker

steps:
  percy:
    image: node:20
    commands:
      - npm ci --no-audit --no-fund
      - npx percy upload ./shots || true
    environment:
      PERCY_PARALLEL_TOTAL: "-1"
    secrets:
      - PERCY_TOKEN
